### ISSUE TITLE
Long delay if using remote timestamp

### ISSUE THREAD

**Issue by sebastianhelbig** [lrdiv/ember-tick-tock#1]
Great addon! One thing:
I have this computed property which shows the remaining seconds until a specified date (competition.voting_start is a moment.js object)

```
countdownSeconds: Ember.computed('competition.voting_start', 'ticktock.now', function() {
    return this.get('competition.voting_start').diff(this.get('ticktock.now'), 'seconds');
}),
```

If _not_ using remote timestamps, the site is loaded and the timer starts counting down the seconds immediately. If using remote timestamps, it shows the seconds _12309_ and than I have a delay of around 4 seconds. So only after 4 seconds it updates again to _12305_, although the time-request to the server (and all other assets) are resolved in less than 100ms.

**Comment by lrdiv** [comment]
@ktrhn Thanks! I will look into it as soon as possible. Is your remote timestamp endpoint public? If so, do you mind sharing so I can try to reproduce under the same conditions?

**Comment by sebastianhelbig** [comment]
I just noticed, that the problem seems to only exist in Opera (v40). I couldn't reproduce it in any other browser, so it probably hasn't anything to do with ember-tick-tock. Sorry about that. (but I sent you an e-mail with the endpoint nevertheless)
